# Generated by Django 3.2.6 on 2022-08-18 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Database",
            fields=[
                ("uuid", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255, null=True)),
                ("description", models.TextField(null=True)),
                ("url", models.URLField(null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Sequence",
            fields=[
                ("uuid", models.AutoField(primary_key=True, serialize=False)),
                ("sequence", models.TextField(null=True)),
                ("accession", models.CharField(max_length=50, null=True)),
                ("organism", models.CharField(max_length=50, null=True)),
                ("description", models.CharField(max_length=50, null=True)),
                ("gene", models.CharField(max_length=50, null=True)),
                ("relations", models.JSONField(null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EnsemblRecord",
            fields=[
                (
                    "sequence_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="dnarecords.sequence",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("dnarecords.sequence",),
        ),
        migrations.CreateModel(
            name="GenbankRecord",
            fields=[
                (
                    "sequence_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="dnarecords.sequence",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("dnarecords.sequence",),
        ),
        migrations.CreateModel(
            name="Feature",
            fields=[
                ("uuid", models.AutoField(primary_key=True, serialize=False)),
                ("type", models.CharField(max_length=50, null=True)),
                ("location", models.CharField(max_length=50, null=True)),
                (
                    "sequence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dnarecords.sequence",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DatabaseReference",
            fields=[
                ("uuid", models.AutoField(primary_key=True, serialize=False)),
                ("db_xref", models.CharField(max_length=50, null=True)),
                ("database", models.ManyToManyField(to="dnarecords.Database")),
                (
                    "feature",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dnarecords.feature",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
