# Generated by Django 3.2.6 on 2022-08-18 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dnarecords", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="database",
            name="uuid",
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="databasereference",
            name="uuid",
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="feature",
            name="uuid",
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="sequence",
            name="uuid",
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name="SequenceHomology",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("description", models.CharField(max_length=50, null=True)),
                ("type", models.CharField(max_length=50, null=True)),
                (
                    "base_sequence",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="base_sequence",
                        to="dnarecords.sequence",
                    ),
                ),
                (
                    "relation_sequence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="related_sequences",
                        to="dnarecords.sequence",
                    ),
                ),
            ],
        ),
    ]
