# Generated by Django 3.2.6 on 2022-09-03 23:21

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnarecords', '0002_auto_20220824_0650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequencehomology',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('84f765f9-2e77-4dcb-b312-d2db3454af0e')),
        ),
    ]
