# Generated by Django 4.1 on 2022-08-20 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dnarecords", "0003_auto_20220818_0652"),
    ]

    operations = [
        migrations.RenameField(
            model_name="feature",
            old_name="location",
            new_name="raw_location",
        ),
        migrations.RenameField(
            model_name="sequence",
            old_name="description",
            new_name="definition",
        ),
        migrations.AddField(
            model_name="feature",
            name="other_data",
            field=models.JSONField(
                help_text="Other information about the feature. Information which does not fit into the above categories. properties of features may not be consistent across features so this area will contain the general information.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="sequence",
            name="length",
            field=models.IntegerField(null=True),
        ),
    ]
