# Generated by Django 3.2.6 on 2022-09-03 23:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dnarecords', '0003_alter_sequencehomology_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequencehomology',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('11f8c651-ce69-4844-b9bc-050155c5f2af')),
        ),
    ]
