# Generated by Django 4.1 on 2022-08-20 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dnarecords", "0004_rename_location_feature_raw_location_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="databasereference",
            name="text",
            field=models.CharField(
                help_text="Original text of the reference", max_length=50, null=True
            ),
        ),
        migrations.AddField(
            model_name="feature",
            name="end_location",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="feature",
            name="start_location",
            field=models.IntegerField(null=True),
        ),
    ]
