# Generated by Django 3.2.6 on 2022-09-09 08:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dnarecords', '0004_alter_sequencehomology_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequencehomology',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('4340781e-9abf-4d0f-93ec-230d16457f77')),
        ),
    ]
