# Generated by Django 4.1 on 2022-08-20 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "dnarecords",
            "0006_alter_database_uuid_alter_databasereference_uuid_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="sequence",
            name="mol_type",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
