# Generated by Django 4.1 on 2022-08-20 05:36

import django.db.models.deletion

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dnarecords", "0007_sequence_mol_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="databasereference",
            name="database",
        ),
        migrations.AddField(
            model_name="databasereference",
            name="database",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="dnarecords.database",
            ),
        ),
    ]
