# Generated by Django 4.1.1 on 2022-09-27 05:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("dnarecords", "0007_alter_sequencehomology_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sequencehomology",
            name="uuid",
            field=models.UUIDField(
                default=uuid.UUID("7d22fc18-9be0-4622-b0b4-bea50d846900")
            ),
        ),
    ]
