# Generated by Django 4.1.1 on 2022-09-27 08:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("dnarecords", "0008_alter_sequencehomology_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sequencehomology",
            name="uuid",
            field=models.UUIDField(
                default=uuid.UUID("9e27a110-e9e5-4af2-b442-bc9fdbeab920")
            ),
        ),
    ]
