# Generated by Django 3.2.6 on 2022-11-07 04:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dnarecords', '0010_alter_sequencehomology_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequencehomology',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('dcd7ac02-b6c9-4d1a-9194-ea06a6e398fd')),
        ),
    ]
