# Generated by Django 4.1.1 on 2022-11-07 05:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("dnarecords", "0011_alter_sequencehomology_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sequencehomology",
            name="uuid",
            field=models.UUIDField(
                default=uuid.UUID("0689b6b8-f16e-48f0-91dc-fe2ff0d80603")
            ),
        ),
    ]
