# Generated by Django 4.1.1 on 2022-11-07 05:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("dnarecords", "0013_alter_sequencehomology_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sequencehomology",
            name="uuid",
            field=models.UUIDField(
                default=uuid.UUID("313c2019-8dd5-4ebc-94d3-69212980e5aa")
            ),
        ),
    ]
