# Generated by Django 3.2.6 on 2022-11-09 23:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dnarecords', '0014_alter_sequencehomology_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequencehomology',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('78530979-8ae1-4c9f-97bc-396131b26087')),
        ),
    ]
