# Generated by Django 3.2.6 on 2022-11-09 23:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dnarecords', '0015_alter_sequencehomology_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequencehomology',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('4f95a923-f304-472a-9b1c-a1376d22c6f3')),
        ),
    ]
