# Generated by Django 4.1.1 on 2022-11-09 23:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("dnarecords", "0016_alter_sequencehomology_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sequencehomology",
            name="uuid",
            field=models.UUIDField(
                default=uuid.UUID("0512a074-2d5e-4095-8e60-08894d3d46fe")
            ),
        ),
    ]
