# Generated by Django 4.1.1 on 2022-11-09 23:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("dnarecords", "0017_alter_sequencehomology_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sequencehomology",
            name="uuid",
            field=models.UUIDField(
                default=uuid.UUID("969e875b-6386-4dbd-b727-a088e3ce7d31")
            ),
        ),
    ]
