# Generated by Django 3.2.6 on 2022-11-11 01:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dnarecords', '0018_alter_sequencehomology_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequencehomology',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('dbcd2968-0e16-4cfc-b6ee-a1436da9c1c9')),
        ),
    ]
