# Generated by Django 4.1 on 2022-09-13 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gene", "0003_auto_20220909_0831"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gene",
            name="kegg_id",
        ),
    ]
