# Generated by Django 4.1 on 2022-09-13 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gene", "0004_remove_gene_kegg_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="cds",
            name="kegg_id",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="gene",
            name="kegg_id",
            field=models.CharField(max_length=64, null=True),
        ),
    ]
