# Generated by Django 4.1.1 on 2022-09-27 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gene", "0005_cds_kegg_id_gene_kegg_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="cds",
            name="locus",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="gene",
            name="locus",
            field=models.CharField(max_length=64, null=True),
        ),
    ]
