# Generated by Django 4.1.1 on 2022-09-27 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gene", "0007_cds_raw_location_gene_raw_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="gene",
            name="first_base",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="gene",
            name="last_base",
            field=models.IntegerField(null=True),
        ),
    ]
