# Generated by Django 4.1.1 on 2022-11-07 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gene", "0008_gene_first_base_gene_last_base"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cds",
            name="name",
            field=models.CharField(default="", max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="gene",
            name="name",
            field=models.CharField(default="", max_length=256, null=True),
        ),
    ]
