# Generated by Django 3.2.6 on 2022-11-09 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dnarecords', '0016_alter_sequencehomology_uuid'),
        ('gene', '0009_alter_cds_name_alter_gene_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrthologReference',
            fields=[
                ('databasereference_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dnarecords.databasereference')),
            ],
            options={
                'abstract': False,
            },
            bases=('dnarecords.databasereference',),
        ),
        migrations.CreateModel(
            name='QuestGene',
            fields=[
                ('gene_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gene.gene')),
                ('uniprot_accession', models.CharField(max_length=256)),
                ('reference_text', models.CharField(max_length=256)),
                ('file_name', models.CharField(max_length=256)),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orthologs.orthologreference')),
            ],
            options={
                'abstract': False,
            },
            bases=('gene.gene',),
        ),
    ]
