# Generated by Django 4.1.1 on 2022-11-09 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orthologs", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="questgene",
            name="reference",
        ),
        migrations.AddField(
            model_name="questgene",
            name="reference",
            field=models.ManyToManyField(to="orthologs.orthologreference"),
        ),
    ]
