# Generated by Django 4.1.1 on 2022-11-09 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orthologs", "0002_remove_questgene_reference_questgene_reference"),
    ]

    operations = [
        migrations.AddField(
            model_name="questgene",
            name="oma_reference_id",
            field=models.CharField(max_length=256, null=True),
        ),
    ]
